name: Build

on: workflow_dispatch

jobs:
  Audit-Pull-Request:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Setup yarn
        run: npm install -g yarn
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('yarn.lock')}}
          restore-keys: node_modules-
      - name: Install node_modules
        run: yarn
      - name: Build TypeScript
        run: yarn run build
      - name: Build Windows
        run: yarn run build:wx
      - name: Build MacOS
        run: yarn run build:mx
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: ./Jeta-darwin-arm64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ./Jeta-win32-x64
      - name: Report status
        run: echo "audit=success" >> $GITHUB_OUTPUT
